services:
  frontend:
    build: 
      context: .
      dockerfile: packages/questionnaire-fe/Dockerfile
    ports:
      - "8877:80"  # 将主机的 8877 端口映射到容器的 80 端口
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: packages/questionnaire-be/Dockerfile
    ports:
      - "8879:8879"  # 将主机的 8879 端口映射到容器的 8879 端口
    depends_on:
      - redis
      - db
    environment:
      # 你可以在这里添加后端需要的环境变量
      DB_HOST: db
      DB_PORT: 3307
      REDIS_HOST: redis
      REDIS_PORT: 6379
    # 如果有数据库或其他外部服务，可以在这里指定它们
    # networks:
    #   - mynetwork
    # volumes:
    #   - ./packages/questionnaire-be/logs:/app/logs

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=questionnaire_db
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: