# 服务器配置
app:
  port: 8879
  prefix: '/api'
# 数据库配置
db:
  type: 'mysql'
  host: 'localhost'
  username: 'root'
  password: '12345678'
  database: 'questionnaire_db'
  port: 3306
  synchronize: true
  autoLoadEntities: true
  keepConnectionAlive: true
mongo:
  uri: 'mongodb://localhost:27017/questionnaire_mongo_db'
