# 服务器配置
app:
  domain: 'http://localhost' # 服务器域名
  port: 8879 # 服务器端口
  prefix: '/api' # 接口前缀
  jwt:
    secret: 'secret' # jwt密钥
    expiresIn: '1d' # jwt过期时间
# 数据库配置
db:
  mysql:
    type: 'mysql'
    host: 'localhost'
    username: 'root'
    password: '12345678'
    database: 'questionnaire_db'
    port: 3306
    synchronize: true
    autoLoadEntities: true
    keepConnectionAlive: true
  mongo:
    uri: mongodb://admin:12345678@localhost:27017/questionnaire_mongo_db
  redis:
    uri: 'redis://localhost:6379'
# 邮件配置
mailer:
  user: 'XMquestionnaire@163.com'
  pass: 'HS35qYhKHX8UF5kE'
  host: 'smtp.163.com'
  port: 465
# 大模型 API 配置
openai:
  deepseek:
    model: 'deepseek-chat'
    apiKey: 'sk-2edf4f402e524747923f625f5154e808'
    baseURL: 'https://api.deepseek.com'
  qwen-max:
    model: 'qwen-max'
    apiKey: 'sk-746e24bbb3d14fc7bced0a4d35453a41'
    baseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
  qwen-plus:
    model: 'qwen-plus'
    apiKey: 'sk-746e24bbb3d14fc7bced0a4d35453a41'
    baseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
  deepseek-r1:
    model: 'deepseek-r1'
    apiKey: 'sk-746e24bbb3d14fc7bced0a4d35453a41'
    baseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
  deepseek-v3:
    model: 'deepseek-v3'
    apiKey: 'sk-746e24bbb3d14fc7bced0a4d35453a41'
    baseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
