name: Docker Build and Push

on:
  push:
    tags:
      - "v*" # 匹配以 "v" 开头的 Tag，例如 v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. 登录到阿里云容器镜像仓库
      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_URL }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      # 4. 获取版本号（从 lerna.json 中读取）
      - name: Get version from lerna.json
        id: get-version
        run: |
          VERSION=$(node -p "require('./lerna.json').version")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      # 5. 构建并推送 Docker 镜像
      - name: Build and push Docker images
        run: |
          pnpm run build:docker-images-and-push-to-registry
        env:
          ALIYUN_REGISTRY_URL: ${{ secrets.ALIYUN_REGISTRY_URL }}
          ALIYUN_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
          FRONTEND_IMAGE_NAME: ${{ secrets.FRONTEND_IMAGE_NAME }}
          BACKEND_IMAGE_NAME: ${{ secrets.BACKEND_IMAGE_NAME }}
          FRONTEND_DOCKERFILE_PATH: ${{ secrets.FRONTEND_DOCKERFILE_PATH }}
          BACKEND_DOCKERFILE_PATH: ${{ secrets.BACKEND_DOCKERFILE_PATH }}
